name: Rails - Run tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://127.0.0.1:5432

    services:
      mysql:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.19.1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Create database
        run: bin/rails db:setup
      - name: yarn
        run: yarn install
      - name: Build frontend
        run: yarn build
      - name: Run tests
        run: bin/rails test
